services:
  www:  
    build: .  
    ports:
      - "82:80"
    container_name: php_www
    volumes:
      - ./:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sistema_db
    restart: always
    environment:
      MYSQL_DATABASE: sistema
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./sistema.sql:/docker-entrypoint-initdb.d/sistema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:
